apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-1
  labels:
    app: example-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app-1
  template:
    metadata:
      labels:
        app: example-app-1
    spec:
      containers:
        - name: app
          image: docker.io/tanvanat/example-app-1:0.0.2 # {"$imagepolicy":"default:example-app-1"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
