apiVersion: v1
kind: Service
metadata:
  name: example-app-1
spec:
  selector:
    app: example-app-1
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  type: ClusterIP
