apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-nipa-instance
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./kubernetes/fluxcd/repositories/infra-repo/openstack   # <== แก้ตรงนี้ให้ตรงตำแหน่งจริง
  sourceRef:
    kind: GitRepository
    name: infra-repo
    namespace: flux-system
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: ncs-openstack-cred

